### ISSUE TITLE
Fix failing build

### ISSUE THREAD

**Issue by Hiccup-za** [njord-rs/docs#2]
After the changes I made to the docs, the build is failing:

- https://github.com/njord-rs/docs/actions/runs/11323074068

Failure is due to: `Unable to resolve action atiltedtree/setup-rust, repository not found`

**Comment by mjovanc** [comment]
Could you take a look at this @Hiccup-za? If you have time and know how to fix it? Otherwise I will take a look at it.

**Comment by Hiccup-za** [comment]
Will take a look from my side and see if I can figure it out 💪
